config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :games, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  include PgSearch
  pg_search_scope :search_for_best_game, :against => [:player_count, :duration, :box_size, :genre, :card_or_board]
  def self.make_array
    array = []
    @games = self.all
    @games.each do |game|
      array << game
    end
    array
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @a_number = -1
    @player_requirements = params
    @games = Game.search_for_best_game("#{params[:player_count]} #{params[:duration].split[0]} #{params[:box_size]} #{params[:genre]} #{params[:card_or_board]}")
    random_array = []
    @games = Game.all if @games.first.nil?
    @games.each {|game| random_array << game}
    @game = random_array.sample

    if params[:random]
      @a_number = 1
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_layout_index.html.erb
<div class="body-container-index">
  <div class="index-container">
    <div class="games-title">
      <h2 class= "new-font">Your desired games</h2>
    </div>

    <div class="back-container">
      <%= link_to 'Go Back', root_path, class: 'btn btn-primary back' %>
    </div>
    <div class="container">
      <div class="row">
        <% @games.each do |game| %>
        <div class="col-sm-12 col-md-6">
          <div class="games-container-card">
            <div class="games-image-card">
              <%= image_tag("#{game.image}", size: "300x200", alt: "Edit Entry") %>
            </div>
            <div class="card-description">
              <div>
                <h4 class= "new-font"><%= game.name %></h4>
                <p>Players: <%= game.player_count[0] %>-<%= game.player_count.split[-1] %></p>
                <p>Duration: <%= game.duration %></p>
                <p>Genres: <%= game.genre %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/games/_layout_show.html.erb
<div class="body-container-show">

  <div class="show-container">
    <div class="game-name-container">
      <h3 class="new-font"><%= @game.name %></h3>
    </div>
    <div class="back-container">
      <%= link_to 'Go Back', root_path, class: 'btn btn-primary back' %>
      <%= link_to "Refresh", {"utf8"=>"✓", "player_count"=>"#{@player_requirements["player_count"]}", "duration"=>"#{@player_requirements["duration"]}", "box_size"=>"", "genre"=>"#{@player_requirements["genre"]}", "card_or_board"=>"#{@player_requirements["card_or_board"]}", "random"=>"Find a random game!", "controller"=>"games", "action"=>"index"}, class: "btn btn-primary back"%>
    </div>
    <div class="game-container">
      <div class="image-container">
        <%= image_tag("#{@game.image}", size: "600x600", alt: "Edit Entry") %>
      </div>
      <div class="game-info-container">
        <h3>Game Info</h3>
        <p>Players: <%= @game.player_count[0] %>-<%= @game.player_count.split[-1] %></p>
        <p>Duration: <%= @game.duration %></p>
        <p>Genres: <%= @game.genre %></p>
        <p>This is a <%= @game.card_or_board %> game</p>
      </div>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<% if @a_number == -1 %>
  <%= render 'layout_index', games: @games %>
<% else %>
  <%= render 'layout_show', game: @game %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>BoredGames</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('chess-piece.png'), :rel => 'icon', :type =>  'image/png' %>
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400" rel="stylesheet">
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_form_all.html.erb
<%= form_tag games_path, method: :get do %>
  <%= number_field_tag :player_count, params[:player_count], class: "form-control margin-down",placeholder: "How many players?"
    %>
  <%= select_tag :duration, "<option>Quick (1-15min)</option><option>Short (15-40min)</option><option>Average (40-90min)</option><option>Long (90+min)</option>".html_safe, prompt: "How long should the game be?", class: "form-control margin-down" %>
  <%= number_field_tag :box_size, params[:box_size], class: "form-control margin-down",placeholder: "How big should the box be (if youre a weirdo and care about this stuff)"
    %>
  <%= select_tag :genre, "<option>Party</option><option>Resource</option><option>Strategy</option><option>Trivia</option><option>Co-op</option><option>Dexterity</option><option>Classic</option><option>Puzzle</option><option>Luck</option><option>Bluff</option><option>Collection</option>".html_safe, class: "form-control margin-down", prompt: "Pick a genre" %>
  <%= select_tag :card_or_board, "<option>Board</option><option>Card</option>".html_safe, class: "form-control margin-down", prompt: "Board or Card game?" %>
  <%= submit_tag "Give me a List!", class: "btn btn-primary" %>
  <%= submit_tag "Find a random game!", name: "random", class: "btn btn-primary" %>
<% end %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="title-content">
    <h1 class="new-font">Welcome to boredGames!</h1>
  </div>
  <div class="banner-content">
    <div class="form-container">
      <h3 class="new-font">Which games fit your needs?</h3>
      <%= render 'form_all' %>
    </div>
  </div>
</div>